export const colummns = [
  {
    name: "id",
    value: "id",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Họ và tên",
    value: "name",
    width: "200px",
    action: false,
    align: "center",
  },
   {
    name: "Tên phụ huynh",
    value: "parent",
    width: "200px",
    action: false,
    align: "center",
  },
  {
    name: "Lớp",
    value: "classroom",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Hình ảnh",
    value: "profile_image",
    width: "200px",
    action: false,
    align: "center",
    type:'image'
  },
  {
    name: "Giới tính",
    value: "gender",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Địa chỉ",
    value:'address',
    width: "250px",
    action: true,
    align: "center",
  },
  {
    name: "Ngày sinh",
    value:'date_of_birth',
    width: "150px",
    action: true,
    align: "center",
  },
  {
    name: "Số điện thoại",
    value:'phone_number',
    width: "200px",
    action: true,
    align: "center",
  },
  {
    name: "Email",
    value:'email',
    width: "200px",
    action: true,
    align: "center",
  },
];

export const colummnsAccount = [
  {
    name: "id",
    value: "id",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Họ và tên",
    value: "name",
    width: "200px",
    action: false,
    align: "center",
  },
  {
    name: "Vai trò",
    value: "role",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Hình ảnh",
    value: "profile_image",
    width: "200px",
    action: false,
    align: "center",
    type:'image'
  },
  {
    name: "Giới tính",
    value: "gender",
    width: "100px",
    action: false,
    align: "center",
  },
  {
    name: "Địa chỉ",
    value:'address',
    width: "250px",
    action: true,
    align: "center",
  },
  {
    name: "Ngày sinh",
    value:'date_of_birth',
    width: "150px",
    action: true,
    align: "center",
  },
  {
    name: "Số điện thoại",
    value:'phone_number',
    width: "200px",
    action: true,
    align: "center",
  },
  {
    name: "Email",
    value:'email',
    width: "200px",
    action: true,
    align: "center",
  },
];