export const colummns = [
    {
      name: "id",
      value: "id",
      width: "100px",
      action: false,
      align: "center",
    },
    {
      name: "Họ và tên",
      value: "name",
      width: "200px",
      action: false,
      align: "center",
    },
     {
      name: "Tên phụ huynh",
      value: "name",
      width: "200px",
      action: false,
      align: "center",
    },
    {
      name: "Lớp",
      value: "class",
      width: "100px",
      action: false,
      align: "center",
    },
    {
      name: "Hình ảnh",
      value: "img",
      width: "200px",
      action: false,
      align: "center",
      type:'image'
    },
    {
      name: "Giới tính",
      value: "gender",
      width: "200px",
      action: false,
      align: "center",
    },
    {
      name: "Địa chỉ",
      value:'address',
      width: "200px",
      action: true,
      align: "center",
    },
    {
      name: "Ngày sinh",
      value:'date',
      width: "200px",
      action: true,
      align: "center",
    },
    {
      name: "Số điện thoại",
      value:'phone',
      width: "200px",
      action: true,
      align: "center",
    },
    {
      name: "Email",
      value:'email',
      width: "200px",
      action: true,
      align: "left",
    },
  ];